# Setup
title:               James's Blog
url:                 https://jtconnor.github.io
paginate:            5
baseurl:             ""

# google analytics
analytics_id: UA-101158951-1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              James Connor

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
